
# R/utils-import.R

#' @import org.Mm.eg.db
#' @importFrom Seurat Read10X_Coordinates
#' @importFrom Seurat Read10X_h5
#' @importFrom Seurat CreateSeuratObject
#' @importFrom Seurat PercentageFeatureSet
#' @importFrom Seurat FindNeighbors
#' @importFrom Seurat FindClusters
#' @importFrom Seurat NormalizeData
#' @importFrom Seurat ScaleData
#' @importFrom Seurat RunPCA
#' @importFrom Seurat RunUMAP
#' @importFrom Seurat DimPlot
#' @importFrom Seurat FindVariableFeatures
#' @importFrom Seurat VariableFeatures
#' @importFrom Seurat FindMarkers
#' @importFrom Seurat Embeddings
#' @importFrom Seurat GetAssayData
#' @importFrom mclust Mclust
#' @importFrom mclust mclustBIC
#' @importFrom Giotto createGiottoInstructions
#' @importFrom Giotto createGiottoObject
#' @importFrom Giotto createGiottoImage
#' @importFrom Giotto addGiottoImage
#' @importFrom Giotto spatPlot2D
#' @importFrom Giotto spatFeatPlot2D
#' @importFrom Giotto normalizeGiotto
#' @importFrom Giotto addStatistics
#' @importFrom Giotto createSpatialDelaunayNetwork
#' @importFrom Giotto doHMRF
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggplotGrob
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_violin
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_blank
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 coord_cartesian
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 guide_colorbar
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 scale_fill_gradientn
#' @importFrom ggplot2 scale_fill_gradient
#' @importFrom ggplot2 scale_fill_gradient2
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_size_identity
#' @importFrom ggplot2 scale_size_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 ggplot_build
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 guide_none
#' @importFrom ggplot2 scale_color_gradientn
#' @importFrom ggplot2 scale_colour_manual
#' @importFrom ggplot2 coord_fixed
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 position_jitter
#' @importFrom cowplot ggdraw
#' @importFrom cowplot draw_image
#' @importFrom ggnewscale new_scale_fill
#' @importFrom ggnewscale new_scale_color
#' @importFrom ggnewscale new_scale_colour
#' @importFrom scales hue_pal
#' @importFrom scales rescale
#' @importFrom scales alpha
#' @importFrom colorspace qualitative_hcl
#' @importFrom ggplotify as.ggplot
#' @importFrom patchwork patchworkGrob
#' @importFrom patchwork wrap_plots
#' @importFrom patchwork plot_layout
#' @importFrom patchwork plot_annotation
#' @importFrom patchwork plot_spacer
#' @importFrom dplyr bind_rows
#' @importFrom dplyr bind_cols
#' @importFrom dplyr union
#' @importFrom dplyr intersect
#' @importFrom dplyr mutate
#' @importFrom dplyr rename
#' @importFrom dplyr tibble
#' @importFrom Matrix rowSums
#' @importFrom Matrix colSums
#' @importFrom Matrix sparseMatrix
#' @importFrom Matrix Matrix
#' @importFrom Matrix diag
#' @importFrom data.table as.data.table
#' @importFrom data.table rbindlist
#' @importFrom data.table data.table
#' @importFrom data.table setorder
#' @importFrom data.table setorderv
#' @importFrom celldex MouseRNAseqData
#' @importFrom celldex ImmGenData
#' @importFrom SummarizedExperiment colData
#' @importFrom SummarizedExperiment assay
#' @importFrom biomaRt useEnsembl
#' @importFrom biomaRt getBM
#' @importFrom usethis use_data
#' @importFrom clusterProfiler enrichGO
#' @importFrom clusterProfiler gseKEGG
#' @importFrom clusterProfiler enrichKEGG
#' @importFrom clusterProfiler simplify
#' @importFrom simplifyEnrichment GO_similarity
#' @importFrom simplifyEnrichment simplifyGO
#' @importFrom enrichplot cnetplot
#' @importFrom openxlsx createWorkbook
#' @importFrom openxlsx addWorksheet
#' @importFrom openxlsx writeData
#' @importFrom openxlsx saveWorkbook
#' @importFrom viridis plasma
#' @importFrom utils combn
#' @importFrom utils menu
#' @importFrom stats filter
#' @importFrom stats dist
#' @importFrom kernlab rbfdot
#' @importFrom kernlab kernelMatrix
#' @importFrom SingleCellExperiment SingleCellExperiment
#' @importFrom SingleCellExperiment colData
#' @importFrom SingleCellExperiment reducedDim
#' @importFrom BayesSpace spatialCluster
#' @importFrom ggvenn ggvenn
#' @importFrom tibble as_tibble
#' @importFrom tibble rownames_to_column
#' @importFrom tibble column_to_rownames
#' @importFrom readr read_csv
#' @importFrom progeny progeny
#' @importFrom sparseMatrixStats rowVars
#' @importFrom RColorBrewer brewer.pal
#' @importFrom magick image_read

NULL
